version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: sparkles-centrifugal_centrifugo_1
      APP_PORT: 8000

  centrifugo:
    image: centrifugo/centrifugo:v4.0.0
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535