version: "2.1"
services:
  app_proxy:
    environment:
      APP_HOST: sparkles-ngircd_ngircd_1
      APP_PORT: 6667
  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${EXPORTS_APP_DIR}/config:/config