version: '3'
services:
  app_proxy:
    environment:
      APP_HOST: sparkles-molior_molior_1
      APP_PORT: 80
  molior:
    container_name: molior
    image: neolynx/molior
    volumes:
      - ${EXPORTS_APP_DIR}/molior_data:/var/lib/molior:rw
      - ${EXPORTS_APP_DIR}/postgres_data:/var/lib/postgresql:rw
    depends_on:
      - aptly
    environment:
      - DEBSIGN_NAME=Molior
      - DEBSIGN_EMAIL=debsign@docker
      - REPOSIGN_EMAIL=reposign@docker
      - MOLIOR_ADMIN_PASSWD=secret77
      - APTLY_USER=molior
      - APTLY_PASS=secret77
      - APTLY_PUBLIC_URL=http://localhost:3142
  aptly:
    container_name: aptly
    image: neolynx/molior-aptly
    volumes:
      - ${EXPORTS_APP_DIR}/aptly_data:/var/lib/aptly:rw
    environment:
      - REPOSIGN_NAME=Molior
      - REPOSIGN_EMAIL=reposign@docker
      - APTLY_USER=molior
      - APTLY_PASS=secret77
    ports:
      - "3142:3142"