version: "3"
services:
  app_proxy:
    environment:
      APP_HOST: sparkles-hello-world_web_1
      APP_PORT: 81
  web:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: on-failure
    stop_grace_period: 1m
    ports:
      # These ports are in format <host-port>:<container-port>
      - '${APP_NPROXYMANAGER_HTTP_PORT}:80' # Public HTTP Port
      - '${APP_NPROXYMANAGER_HTTPS_PORT}:443' # Public HTTPS Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ${APP_NPROXYMANAGER_DATA_DIR}:/data
      - ${APP_NPROXYMANAGER_LETSENCRYPT_DIR}:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ${APP_NPROXYMANAGER_MYSQL_DIR}:/var/lib/mysql