export APP_NPROXYMANAGER_IP="10.21.21.63"
export APP_NPROXYMANAGER_ADMIN_PORT=22281
export APP_NPROXYMANAGER_HTTP_PORT=22280
export APP_NPROXYMANAGER_HTTPS_PORT=22443
export APP_NPROXYMANAGER_DATA_DIR="${EXPORTS_APP_DIR}/data"
export APP_NPROXYMANAGER_LETSENCRYPT_DIR="${EXPORTS_APP_DIR}/letsencrypt"
export APP_NPROXYMANAGER_MYSQL_DIR="${EXPORTS_APP_DIR}/mysql"